<?xml version="1.0" encoding="UTF-8"?>
<!--
資料名稱: 臺灣出版新書預告書訊
收錄期間: 本資料與全國新書資訊網「書目下載/批次下載」每月同步更新，本次更新申請日期: 20170401~20170430 區間的資料。
說　　明: 本資料集內容屬我國即將出版之新書，向國家圖書館國際標準書號中心申請國際標準書號（ISBN）之新書書目資訊。正式出版後時有異動，請以正式出版之書目資料為準。
-->
<!DOCTYPE Book [
<!ELEMENT Book (書名, 作者, 出版單位, 版次, 出版年月, 標題, 適讀對象, 類號, ISBN)>
<!ELEMENT 書名 (#PCDATA)>
<!ELEMENT 作者 (#PCDATA)>
<!ELEMENT 出版單位 (#PCDATA)>
<!ELEMENT 版次 (#PCDATA)>
<!ELEMENT 出版年月 (#PCDATA)>
<!ELEMENT 標題 (#PCDATA)>
<!ELEMENT 適讀對象 (#PCDATA)>
<!ELEMENT 類號 (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
]>
<Books>
	<Book>
		<書名>全彩、全圖解、全實景地表最狂日文單字王</書名>
		<作者>須永賢一著</作者>
		<出版單位>不求人文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.日語 2.詞彙</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>803.12</類號>
		<ISBN>978-986-94529-4-6 (平裝附光碟片, NT$299, 576面, 17公分)</ISBN>
	</Book>
	<Book>
		<書名>Measurement of joint motion: a guide to goniometry</書名>
		<作者>By Cynthia C. Norkin, D. Joyce White</作者>
		<出版單位>合記</出版單位>
		<版次>5th ed.</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-368-182-3 (平裝, 592面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>3小時讀通基礎機械製圖</書名>
		<作者>門田和雄作; 衛宮紘譯		</作者>
		<出版單位>世茂</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.機械設計 2.工程圖學</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>446.194</類號>
		<ISBN>978-986-94562-8-9 (平裝, NT$300, 208面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>生態觀光</書名>
		<作者>謝文豐作</作者>
		<出版單位>揚智文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.生態旅遊 2.環境保護 3.自然保育</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>992</類號>
		<ISBN>978-986-298-259-4 (平裝, NT$550, 416面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>創意: 意識創造暨實務:  浪漫台3線計劃提案手冊</書名>
		<作者>洪燕梅, 高詩茹, 林宥全編</作者>
		<出版單位>洪燕梅</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4498-7 (平裝, 180面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>媒觀析: 台灣媒體觀察報告. 2016年</書名>
		<作者>王怡蓁等作</作者>
		<出版單位>臺灣媒體觀察教育基金會</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題>1.媒體 2.傳播政策 3.傳播史 4.臺灣</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>541.839</類號>
		<ISBN>978-986-84518-2-7 (平裝, NT$100, 56面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>從海洋看歷史</書名>
		<作者>小島毅監修; 羽田正編集; 張雅婷譯</作者>
		<出版單位>廣場</出版單位>
		<版次>一版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.外交史 2.文化史 3.航運史 4.東亞</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>730.1</類號>
		<ISBN>978-986-94088-4-4 (平裝, NT$360, 288面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>情熱</書名>
		<作者>宋雨桐著</作者>
		<出版單位>果樹</出版單位>
		<版次>初版</版次>
		<出版年月>106/07</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-94327-4-0 (平裝, NT$200, 232面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>科學起步走: 激發3-7歲孩子好奇探究的89個活動</書名>
		<作者>William C. Ritz作; 劉淑雯等譯</作者>
		<出版單位>華騰文化</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題>1.Science 2.科學教育 3.教學活動設計 4.小學教學</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>523.36</類號>
		<ISBN>978-986-447-075-4 (平裝, NT$550, 420面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>悌道訪遊記</書名>
		<作者>無極直轄全真堂著</作者>
		<出版單位>全真雜誌</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-88139-5-3 (平裝, 176面, 17公分)</ISBN>
	</Book>
	<Book>
		<書名>迷你退休</書名>
		<作者>黃千碩著</作者>
		<出版單位>集夢坊</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.退休 2.自我實現 3.生活指導</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>544.83</類號>
		<ISBN>978-986-94538-2-0 (平裝, 288面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>快樂讀經典: 春秋故事</書名>
		<作者>林漢達著; 劉安利繪</作者>
		<出版單位>遠見天下文化</出版單位>
		<版次>二版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>859.6</類號>
		<ISBN>978-986-479-218-4 (平裝, NT$280, 216面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>霜鬢話當年</書名>
		<作者>賴和鴻作</作者>
		<出版單位>賴和鴻</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.賴和鴻 2.臺灣傳記</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>783.3886</類號>
		<ISBN>978-957-43-4469-7 (平裝, 288面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>親愛的世界,你好嗎?一個5歲小男孩從一枝鉛筆、一張明信片開始的193國環球旅行</書名>
		<作者>托比.里特(Toby Little)著; 林欣璇譯</作者>
		<出版單位>臉譜</出版單位>
		<版次>二版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>873.6</類號>
		<ISBN>978-986-235-583-1 (平裝, NT$320, 284面, 22公分)</ISBN>
	</Book>
	<Book>
		<書名>一眼就突破盲點的思考力: 破解假數字、偽科學、不實資訊背後的真相</書名>
		<作者>丹尼爾.列維廷(Daniel J. Levitin)著; 曹嬿恆譯</作者>
		<出版單位>商周</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.Critical thinking 2.Fallacies (Logic) 3.Reasoning 4.企業經營 5.決策管理 6.謬誤</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>494.1</類號>
		<ISBN>978-986-477-226-1 (平裝, NT$360, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>鋼鐵人的盔甲值多少錢?</書名>
		<作者>朴炳律著</作者>
		<出版單位>商周</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.經濟學 2.通俗作品</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>550</類號>
		<ISBN>978-986-477-227-8 (平裝, NT$350, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>族譜學論集</書名>
		<作者>陳捷先著</作者>
		<出版單位>三民</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.族譜 2.文集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>789.107</類號>
		<ISBN>978-957-14-6288-2 (平裝, 459面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>藝術傳承</書名>
		<作者>黃明志作</作者>
		<出版單位>亞洲藝術學會</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.兒童畫 2.畫冊</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>947.47</類號>
		<ISBN>978-986-91612-2-0 (精裝, NT$1200, 96面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>黃埔軍校第三期生全記錄</書名>
		<作者>陳予歡著</作者>
		<出版單位>思行文化傳播</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.軍官 2.傳記 3.中華民國</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>590.992</類號>
		<ISBN>978-986-92736-7-1 (全套:平裝, NT$2400, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>臺灣總督府檔案學習入門</書名>
		<作者>徐國章著</作者>
		<出版單位>國史館臺灣文獻館</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.史料 2.檔案管理 3.日據時期 4.臺灣史</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>733.28</類號>
		<ISBN>978-986-05-2295-2 (平裝, NT$1000, 400面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>樂樂聽讀兒童高級故事(簡體字版)</書名>
		<作者>[姚釹, 李琇琇作]</作者>
		<出版單位>臺灣樂樂文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93872-2-4 (全套:平裝, 17公分)</ISBN>
	</Book>
	<Book>
		<書名>長榮大學書畫藝術學系畢業專刊. 第四屆</書名>
		<作者></作者>
		<出版單位>長榮大學書畫藝術系</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題>1.書畫 2.作品集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>941.6</類號>
		<ISBN>978-986-6358-46-3 (平裝, 120面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>打拼顧自己: 高雄市登革熱防疫理論與實務</書名>
		<作者>黃志中主編</作者>
		<出版單位>高市衛生局</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.登革熱 2.病媒防制</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>412.4923</類號>
		<ISBN>978-986-05-2298-3 (平裝, 260面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>誦詩 詠文 策筆</書名>
		<作者>林素珍作</作者>
		<出版單位>教育部</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題>1.閱讀指導 2.中等教育</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>524.31</類號>
		<ISBN>978-986-05-2302-7 (平裝, NT$320, 220面, 28公分)</ISBN>
	</Book>
	<Book>
		<書名>她殺了時代: 重訪日本電影新浪潮</書名>
		<作者>牛頭犬等作</作者>
		<出版單位>高市電影館</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.電影片 2.影評 3.日本</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>987.931</類號>
		<ISBN>978-986-05-2303-4 (平裝, NT$380, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>敦煌風華再現: 續說石窟故事</書名>
		<作者>劉憶諄, 李作婷, 何恭算文字編撰</作者>
		<出版單位>自然科學博物館</出版單位>
		<版次>第一版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.佛教藝術 2.石窟藝術</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>224.52</類號>
		<ISBN>978-986-05-2304-1 (精裝, NT$680, 240面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>散戶醒思</書名>
		<作者>周錦成著</作者>
		<出版單位>周錦成</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.股票投資 2.投資技術 3.投資分析</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>563.53</類號>
		<ISBN>978-957-43-4473-4 (平裝, NT$200, 112面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>信用狀統一慣例實務</書名>
		<作者>蔡輝端著</作者>
		<出版單位>蔡輝端</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.信用狀</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>563.25</類號>
		<ISBN>978-957-43-4474-1 (精裝, NT$850, 453面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>歲時祭禮與擇日: 以臺北五大家族為例(陳悅記、許標重、仙景李氏、劉和林、林成祖)</書名>
		<作者>林育名著</作者>
		<出版單位>林育名</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題>1.家禮 2.民間信仰 3.擇日</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>534</類號>
		<ISBN>978-957-43-4475-8 (平裝, NT$500, 296面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>盜國物語</書名>
		<作者>司馬遼太郎作; 馬靜譯</作者>
		<出版單位>遠流</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-32-7987-7 (全套:平裝, NT$1300, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>山海紀: 國立臺東生活美學館年報. 105</書名>
		<作者>田芷芸執行編輯</作者>
		<出版單位>臺東生活美學館</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.國立臺東生活美學館</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>528.4162</類號>
		<ISBN>978-986-05-2305-8 (平裝, NT$200, 88面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>立足聖道的創意禮拜</書名>
		<作者>陳琇玟著</作者>
		<出版單位>台灣神學研究學院</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.基督教 2.宗教儀注</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>244</類號>
		<ISBN>978-986-94709-0-2 (精裝, NT$480, 424面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>你還要療癒多久?: 人類新操作系統. 2, 從療癒走向創造</書名>
		<作者>鍾荃因Doris著</作者>
		<出版單位>商周</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.成功法 2.直覺 3.自我實現</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>177.2</類號>
		<ISBN>978-986-477-228-5 (平裝, NT$320, 224面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>中國人權觀察報告. 2016</書名>
		<作者>[財團法人臺灣民主基金會編]</作者>
		<出版單位>臺灣民主基金會</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93341-1-2 (平裝, 252面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>櫃中美人</書名>
		<作者>水合著</作者>
		<出版單位>春天出版國際</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-986-94698-1-4 (上冊:平裝, NT$399, 464面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>櫃中美人</書名>
		<作者>水合著</作者>
		<出版單位>春天出版國際</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-986-94698-2-1 (下冊:平裝, NT$399, 464面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>不思議な駅: 全台三十四個無人車站寫真</書名>
		<作者>吳洛均著</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次></版次>
		<出版年月>106/05</出版年月>
		<標題>1.臺灣遊記 2.鐵路車站 3.照片集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>733.69</類號>
		<ISBN>978-986-5733-82-7 (精裝, NT$790, 208面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>拾老味</書名>
		<作者>李怡慧, 郭善寧著</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.飲食 2.文集  3.臺灣</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>427.07</類號>
		<ISBN>978-986-5733-83-4 (平裝, NT$500, 64面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>如歌的行板</書名>
		<作者>鍾宜靜, 吳孟緯著</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.流行音樂 2.臺灣傳記 3.訪談</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>910.9933</類號>
		<ISBN>978-986-5733-84-1 (平裝, NT$380, 64面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>柳哥</書名>
		<作者>羅伶育圖.文</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-5733-85-8 (平裝, NT$490, 48面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>如何用氣來保健人體</書名>
		<作者>鄭德相著</作者>
		<出版單位>鄭德相</出版單位>
		<版次>三版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4476-5 (平裝, NT$200, 197面, 31公分)</ISBN>
	</Book>
	<Book>
		<書名>放生護生</書名>
		<作者>妙祥法師講述</作者>
		<出版單位>王堂宇</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4477-2 (平裝, 304面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>少稅一點: 106年最新扣除額</書名>
		<作者>陳膺仁著</作者>
		<出版單位>科寶文化</出版單位>
		<版次>二版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.所得稅</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>567.21</類號>
		<ISBN>978-986-5980-13-9 (平裝, 228面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>文字的旅行: 臺灣活版指南</書名>
		<作者>黃俊夫, 黃湜雯編著</作者>
		<出版單位>文化部文化資產局</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.活字印刷術 2.歷史 3.臺灣</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>477.0933</類號>
		<ISBN>978-986-05-2307-2 (平裝, NT$180, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>少稅一點: 107年最新扣除額</書名>
		<作者>陳膺仁著</作者>
		<出版單位>科寶文化</出版單位>
		<版次>二版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.所得稅</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>567.21</類號>
		<ISBN>978-986-5980-14-6 (平裝, 228面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>Capture your style: IG時尚教主Aimee Song,教你用手機拍出最有型的照片,讓萬人關注你的精彩每一天</書名>
		<作者>Aimee Song作; 曾慧敏譯</作者>
		<出版單位>尖端</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.Photography 2.Online social networks 3.攝影技術 4.數位攝影</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>952</類號>
		<ISBN>978-957-10-7449-8 (平裝, 208面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>跟著貓咪去旅行!環遊世界54國,把你的心遺留在那美好的風景中</書名>
		<作者>小林希作; 林克鴻譯</作者>
		<出版單位>尖端</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.貓 2.照片集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>437.36</類號>
		<ISBN>978-957-10-7450-4 (平裝, 168面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>新巴赫花精療癒: 從情緒及靈性上調理你的身心靈疾病</書名>
		<作者>笛特瑪.柯磊墨(Dietmar Kramer)著; 王真心譯</作者>
		<出版單位>自由之丘文創</出版單位>
		<版次>二版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.自然療法 2.順勢療法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>418.995</類號>
		<ISBN>978-986-94238-3-0 (平裝, NT$360, 288面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>新巴赫花精身體地圖: 與花精對應的皮膚反應部位療癒書</書名>
		<作者>笛特瑪.柯磊墨(Dietmar Kramer), 賀爾姆.維爾特(Helmut Wild)著; 王真心, 黃瀚平譯</作者>
		<出版單位>自由之丘文創</出版單位>
		<版次>二版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.自然療法 2.順勢療法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>418.995</類號>
		<ISBN>978-986-94238-4-7 (平裝, NT$360, 288面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>和大師一起動手: 撰寫一個完整的作業系統</書名>
		<作者>鄭鋼著</作者>
		<出版單位>佳魁資訊</出版單位>
		<版次></版次>
		<出版年月>106/05</出版年月>
		<標題>1.作業系統</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312.54</類號>
		<ISBN>978-986-379-507-0 (線裝, NT$860, 1120面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>前端開發的涅槃: React全面昇華你的FrontEnd境界</書名>
		<作者>陳屹著</作者>
		<出版單位>佳魁資訊</出版單位>
		<版次></版次>
		<出版年月>106/05</出版年月>
		<標題>1.系統程式 2.軟體研發 3.行動資訊</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312.52</類號>
		<ISBN>978-986-379-508-7 (平裝, NT$540, 448面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>結婚注定有道坎</書名>
		<作者>喜格格作</作者>
		<出版單位>新月文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-986-288-790-5 (平裝, NT$210, 272面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>小嫁娘</書名>
		<作者>葉雙作</作者>
		<出版單位>新月文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-986-288-791-2 (平裝, NT$210, 240面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>蜘蛛人角色聖典</書名>
		<作者>Daniel Wallace著; 李玉蘭, 林柏翰, 法蘭克譯</作者>
		<出版單位>奇幻基地</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.漫畫 2.讀物研究</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>947.41</類號>
		<ISBN>978-986-94499-4-6 (精裝, NT$699, 208面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>資訊圖表的技術: 從實例學Excel圖表製作術</書名>
		<作者>Jorge Camoes原著; 胡為君譯</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.Business 2.Electronic spreadsheets 3.Information visualization 4.EXCEL(電腦程式)</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312.49E9</類號>
		<ISBN>978-986-476-388-7 (平裝, 400面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>別笑!我是最有效法語學習書</書名>
		<作者>李京子作; 徐芝琪譯</作者>
		<出版單位>漢宇國際文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.法語 2.讀本</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>804.58</類號>
		<ISBN>978-986-228-395-0 (平裝附光碟片, 288面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>我家的鸚鵡超愛現!</書名>
		<作者>柴田祐未子, 海老沢和荘監修; 彭春美譯</作者>
		<出版單位>漢欣文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.鸚鵡 2.寵物飼養</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>437.39</類號>
		<ISBN>978-957-686-740-8 (平裝, NT$300, 144面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>RESET轉世重生</書名>
		<作者>如月由須羅著; 唯川聿譯</作者>
		<出版單位>天使出版國際文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號>861.57</類號>
		<ISBN>978-986-94674-4-5 (第2冊:平裝, NT$249, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>做粄粿: 回味傳統炊蒸米食,新舊做法全部收錄</書名>
		<作者>徐茂揮, 古麗麗著</作者>
		<出版單位>幸福文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.點心食譜</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>427.16</類號>
		<ISBN>978-986-94174-3-3 (平裝, NT$450, 352面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>圖解:大唐帝國</書名>
		<作者>陳楠作</作者>
		<出版單位>海鴿文化</出版單位>
		<版次>二版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.唐史</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>624.1</類號>
		<ISBN>978-986-392-087-8 (平裝, NT$380, 288面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>降三高蔬果這樣吃最好</書名>
		<作者>陳彥甫著</作者>
		<出版單位>人類智庫數位科技</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.高血壓 2.高三酸甘油脂血症 3.糖尿病 4.食療</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>415.382</類號>
		<ISBN>978-986-373-373-7 (平裝, 192面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>阿泥與星星</書名>
		<作者>邱晴, 許芝瑋作</作者>
		<出版單位>邱晴</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4478-9 (精裝, NT$950, 192面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>美容 流行 英語</書名>
		<作者>徐竹芹編著</作者>
		<出版單位>徐竹芹</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4479-6 (光碟片, NT$100, 130面)</ISBN>
	</Book>
	<Book>
		<書名>慚愧僧文集. 第八集</書名>
		<作者>釋大願著</作者>
		<出版單位>人乘佛刊</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.佛教說法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>225</類號>
		<ISBN>978-957-8504-39-4 (平裝, 272面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>日本免疫療法醫師,教你啟動自愈力,正知正念面對癌症</書名>
		<作者>谷川啟司作; 黃筱涵譯</作者>
		<出版單位>世茂</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.癌症 2.免疫療法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>417.8</類號>
		<ISBN>978-986-94562-6-5 (平裝, NT$300, 250面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>境向: 徐明豐作品集. 2017</書名>
		<作者>徐明豐作</作者>
		<出版單位>豐喜堂</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題>1.油畫 2.版畫 3.複合媒材繪畫 4.畫冊</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>947.5</類號>
		<ISBN>978-986-86683-4-8 (平裝, 84面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>清代宮廷承應開場戲劇本輯校</書名>
		<作者>李躍忠編著</作者>
		<出版單位>蘭臺</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.清代戲曲 2.戲劇劇本 3.劇評</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>834.7</類號>
		<ISBN>978-986-5633-55-4 (平裝, NT$400, 312面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>維生素營養對症大百科</書名>
		<作者>馬莉編著</作者>
		<出版單位>西北國際文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.維生素 2.礦物質 3.食療</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>399.6</類號>
		<ISBN>978-986-94607-3-6 (平裝, 432面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>臺中市醫師公會美展聯誼社巡迴展專輯. 2017</書名>
		<作者>蔡文仁總編輯</作者>
		<出版單位>中市醫師公會美展聯誼社</出版單位>
		<版次></版次>
		<出版年月>106/05</出版年月>
		<標題>1.美術 2.作品集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>902.33</類號>
		<ISBN>978-986-88091-3-0 (平裝, NT$300, 60面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>心雲片片</書名>
		<作者>孫宇彤著作</作者>
		<出版單位>必中</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號>857.63</類號>
		<ISBN>978-986-92590-2-6 (平裝, NT$300, 143面, 29公分)</ISBN>
	</Book>
	<Book>
		<書名>漫畫大英百科. 科技. 3: 尖端科技</書名>
		<作者>BomBom Story文; 李斗源圖; 徐月珠譯</作者>
		<出版單位>三采文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.百科全書 2.兒童讀物 3.漫畫</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>049.41</類號>
		<ISBN>978-986-342-829-9 (精裝, NT$420, 168面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>公案禪語</書名>
		<作者>吳怡著</作者>
		<出版單位>東大</出版單位>
		<版次>三版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.禪宗 2.佛教說法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>226.65</類號>
		<ISBN>978-957-19-3142-5 (平裝, 232面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>讓世界免費: 數位貨幣新革命</書名>
		<作者>劉振友著</作者>
		<出版單位>大是文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.企業管理 2.營銷管理</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>494</類號>
		<ISBN>978-986-94580-4-7 (平裝, NT$340, 288面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>臺灣國內商港海域海氣象觀測分析研究. 105年</書名>
		<作者>廖慶堂等著</作者>
		<出版單位>交通部運研所</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.海洋氣象 2.臺灣</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>444.94</類號>
		<ISBN>978-986-04-7841-9 (平裝, NT$540, 514面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>乙級飲料調製技能檢定學術科完全攻略</書名>
		<作者>全華餐旅研究室編著	</作者>
		<出版單位>全華圖書</出版單位>
		<版次>二版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.飲料 2.考試指南</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>427.4</類號>
		<ISBN>978-986-463-510-8 (平裝, NT$600, 432面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>超譯&lt;&lt;君主論&gt;&gt;領導學: 在生活中遇見馬基維利,讓你洞悉人心,成為職場、人生的贏家</書名>
		<作者>鈴木博毅著; 劉曉慈譯</作者>
		<出版單位>日月文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題>1.馬基維利(Machiavelli, Niccolo, 1469-1527) 2.政治思想 3.君主政治</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>571.4</類號>
		<ISBN>978-986-248-643-6 (平裝, NT$260, 256面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>我會亮乀!</書名>
		<作者>林家荷, 黃虹菱文; 游雅筑, 彭鈺涵圖</作者>
		<出版單位>繪星點點</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>學前兒童</適讀對象>
		<類號></類號>
		<ISBN>978-986-94710-0-8 (上冊:精裝, NT$599, 28面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>我會亮乀!</書名>
		<作者>林家荷, 黃虹菱文; 游雅筑, 彭鈺涵圖</作者>
		<出版單位>繪星點點</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>學前兒童</適讀對象>
		<類號></類號>
		<ISBN>978-986-94710-1-5 (下冊:精裝, NT$599, 28面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>杏林深耕四十年</書名>
		<作者>陳文龍作</作者>
		<出版單位>臺灣商務</出版單位>
		<版次>四版</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>855</類號>
		<ISBN>978-957-05-3079-7 (平裝, 352面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>NVivo11與網路質性研究方法論</書名>
		<作者>劉世閔, 曾世豐, 鍾明倫著</作者>
		<出版單位>五南</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.質性研究 2.電腦軟體</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>501.2029</類號>
		<ISBN>978-957-11-9156-0 (平裝, NT$580, 448面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>四百歲的睡鯊與深藍色的節奏: 在四季的海洋上,從小艇捕捉鯊魚的大冒險</書名>
		<作者>摩頓.史托克奈斯(Morten Stroksnes)著; 郭騰堅譯</作者>
		<出版單位>網路與書</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.Shark fishing 2.Greenland shark 3.Fishing 4.Sailing 5.鯊 6.通俗作品 7.挪威</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>388.591</類號>
		<ISBN>978-986-6841-86-6 (平裝, NT$380, 320面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>動物玩童玩</書名>
		<作者>宋政軒等圖.文</作者>
		<出版單位>屏縣長興國小</出版單位>
		<版次>初版二刷</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號></類號>
		<ISBN>978-986-05-2308-9 (精裝, 54面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>景觀規劃設計</書名>
		<作者>賴哲三編著</作者>
		<出版單位>六合</出版單位>
		<版次>第一版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.景觀工程設計</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>929</類號>
		<ISBN>978-986-91736-6-7 (平裝, NT$650, 446面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>想法轉個彎,就能掌握好心情: 認知療法權威教你,用書寫方式擺脫擾亂的思緒與情緒問題</書名>
		<作者>丹尼斯.格林伯格, 克莉絲汀.A.佩德絲基著; 吳郁芸翻譯</作者>
		<出版單位>大樹林</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.Cognitive therapy 2.Affective disorders 3.心理治療 4.情感疾病</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>178.8</類號>
		<ISBN>978-986-6005-65-7 (平裝, NT$450, 344面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>聖誕夜&#039;s奇幻之旅</書名>
		<作者>曾莛家等圖.文</作者>
		<出版單位>屏縣長興國小</出版單位>
		<版次>初版二刷</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號></類號>
		<ISBN>978-986-05-2309-6 (精裝, 40面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>京都名店麵包</書名>
		<作者>森田三和著</作者>
		<出版單位>精誠資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.點心食譜 2.麵包</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>427.16</類號>
		<ISBN>978-986-94705-1-3 (平裝, NT$350, 128面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>變回我自己</書名>
		<作者>莎賓娜.阿爾特瑪特(Sabina Altermatt)作; Mattea Gianotti繪; 吳羽涵譯</作者>
		<出版單位>東雨文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>學前兒童</適讀對象>
		<類號></類號>
		<ISBN>978-986-94450-6-1 (精裝, NT$280, 28面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>臺灣國際港附近海域海氣象現場調查分析研究. 105年</書名>
		<作者>蔡立宏等著</作者>
		<出版單位>交通部運研所</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.海洋氣象 2.港埠 3.臺灣</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>444.94</類號>
		<ISBN>978-986-05-2310-2 (平裝, NT$290, 290面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>港域近岸底床輸沙之現場觀測研究. 105年</書名>
		<作者>林柏青, 衛紀淮, 何良勝著</作者>
		<出版單位>交通部運研所</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.海洋動力學 2.河口</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>351.982</類號>
		<ISBN>978-986-05-2311-9 (平裝, NT$200, 173面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>我的想像朋友</書名>
		<作者>高橋西作.繪; 黃譯嫻譯</作者>
		<出版單位>東雨文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>學前兒童</適讀對象>
		<類號></類號>
		<ISBN>978-986-94450-7-8 (精裝, NT$280, 40面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>原來愛讚美. 6, 泰雅爾族語兒童詩歌本</書名>
		<作者>李位鼎總編輯</作者>
		<出版單位>使徒</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號></類號>
		<ISBN>978-986-7134-94-3 (平裝附光碟片, NT$250, 48面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>丙級室內配線技能檢定學術科題庫解析</書名>
		<作者>楊正祥, 葉見成編著</作者>
		<出版單位>科友</出版單位>
		<版次>八版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-464-074-4 (平裝, 288面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>燦令聖蕊: 田中裕子作品集</書名>
		<作者>田中裕子[作]</作者>
		<出版單位>敦煌藝術中心</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-91505-4-5 (平裝, NT$1000, 96面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>榮耀的異象與十字架的道路</書名>
		<作者>李常受著</作者>
		<出版單位>臺灣福音書房</出版單位>
		<版次>臺灣修訂一版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-166-374-6 (平裝, 61面, 22公分)</ISBN>
	</Book>
	<Book>
		<書名>獵魔士路西斯</書名>
		<作者>謝伯泓作</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-5733-86-5 (平裝, NT$300, 250面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>精準的失控(簡體字版)</書名>
		<作者>九把刀著</作者>
		<出版單位>大眾國際書局</出版單位>
		<版次></版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-301-792-9 (平裝, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>藝趣人生: 沈禎作品集. 2017</書名>
		<作者>沈禎作</作者>
		<出版單位>中國孔學會</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-30021-6-1 (平裝, NT$600, 60面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>想像力不見了</書名>
		<作者>夏樂.貝利埃(Charlotte Belliere)文; 伊恩.德埃伊(Ian De Haes)圖; 孔繁璐譯</作者>
		<出版單位>薪展文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-94713-0-5 (精裝, NT$280, 40面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>工程技術、管理科學與教育研討會論文集. 2017</書名>
		<作者>黃仁清總編輯</作者>
		<出版單位>東南科大研發處</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-94712-0-6 (平裝, 416面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>Excel 2013教學範本</書名>
		<作者>洪錦魁著</作者>
		<出版單位>深石數位</出版單位>
		<版次>第二版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.EXCEL 2013(電腦程式)</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.49E9</類號>
		<ISBN>978-986-94711-0-7 (平裝, NT$650, 688面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>PowerPoint 2013教學範本</書名>
		<作者>洪錦魁著</作者>
		<出版單位>深石數位</出版單位>
		<版次>第二版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.PowerPoint 2013(電腦程式)</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.49P65</類號>
		<ISBN>978-986-94711-1-4 (平裝, NT$420, 576面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>IOS核心框架開發簡易上手</書名>
		<作者>李俊賢, 王子嘉著</作者>
		<出版單位>深石數位</出版單位>
		<版次></版次>
		<出版年月>106/05</出版年月>
		<標題>1.系統程式 2.電腦程式設計 3.行動資訊</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.52</類號>
		<ISBN>978-986-94711-2-1 (平裝, NT$600, 320面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>動畫圖解資料結構: 使用C++</書名>
		<作者>李春雄著</作者>
		<出版單位>深石數位</出版單位>
		<版次>第三版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.資料結構 2.C++(電腦程式語言)</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.73</類號>
		<ISBN>978-986-94711-3-8 (平裝附光碟, NT$550, 656面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>日記傳奇</書名>
		<作者>葉經柱著</作者>
		<出版單位>葉存芳</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4480-2 (平裝, NT$400, 496面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>使用Visual Basic開發Android App</書名>
		<作者>李春雄著</作者>
		<出版單位>深石數位</出版單位>
		<版次>第二版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.系統程式 2.電腦程式設計 3.BASIC(電腦程式語言)</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.52</類號>
		<ISBN>978-986-94711-4-5 (平裝, NT$520, 656面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>改變歷史的地圖與製圖師: 藏在地圖裡的智識美學與權力遊戲</書名>
		<作者>約翰.克拉克(John O. E. Clark)著; 曾雅瑜著</作者>
		<出版單位>大寫</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-5695-87-3 (PDF, NT$299)</ISBN>
	</Book>
	<Book>
		<書名>改變歷史的地圖與製圖師: 藏在地圖裡的智識美學與權力遊戲</書名>
		<作者>約翰.克拉克(John O. E. Clark)著; 曾雅瑜著</作者>
		<出版單位>大寫</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-5695-88-0 (EPUB, NT$299)</ISBN>
	</Book>
	<Book>
		<書名>無法測量的領導藝術: 跟超級老闆學帶人: 他們不說、沒有人會懂的非典型x跨世代培育人才力</書名>
		<作者>席尼.芬克斯坦(Sydney Finkelstein)著; 廖崇佑譯</作者>
		<出版單位>大寫</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-5695-89-7 (EPUB, NT$380)</ISBN>
	</Book>
	<Book>
		<書名>真佛正見</書名>
		<作者>盧勝彥作</作者>
		<出版單位>大燈文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.民間信仰</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>271.9</類號>
		<ISBN>978-986-5859-66-4 (平裝, NT$260, 224面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>像我們這樣的人: 傷友們的疤痕記事</書名>
		<作者>林巧雯, 曹雯玄, 林沂霈著</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>855</類號>
		<ISBN>978-986-5733-88-9 (平裝, NT$350, 224面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>玩□童玩: 自己的童玩自己選</書名>
		<作者>趙雨儂, 曾俊維, 謝辰渝作</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.生活史 2.童玩 3.臺灣</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>733.4</類號>
		<ISBN>978-986-5733-89-6 (平裝, NT$500, 128面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>我們在時間裡吃飯</書名>
		<作者>陳采綸作</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/05</出版年月>
		<標題>1.飲食 2.文集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>427.07</類號>
		<ISBN>978-986-5733-90-2 (平裝, NT$350, 100面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>當我遠道而來</書名>
		<作者>李雨珊, 劉煒倩作</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>855</類號>
		<ISBN>978-986-5733-91-9 (活頁裝, NT$380, 72面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>實用刑法分則測驗</書名>
		<作者>林培仁編著</作者>
		<出版單位>林培仁</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.刑法分則</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>585.2</類號>
		<ISBN>978-957-43-4481-9 (平裝, NT$450, 500面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>資訊技術與產業應用研討會論文集</書名>
		<作者>臺北城市科技大學資訊管理系作</作者>
		<出版單位>臺北城市科大</出版單位>
		<版次></版次>
		<出版年月>106/04</出版年月>
		<標題>1.資訊技術 2.資訊管理 3.資訊服務業 4.文集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312.07</類號>
		<ISBN>978-986-93241-1-3 (平裝, NT$500, 68面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>口紅印的獨白</書名>
		<作者>王顥諭, 黃曉欣, 簡羚靚作</作者>
		<出版單位>靜宜大學臺文系</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>855</類號>
		<ISBN>978-986-5733-92-6 (平裝, NT$600, 120面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>MTA Security Fundamentals國際認證教戰手冊(98-367)</書名>
		<作者>吳進北, 林文恭研究室著</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.資訊安全 2.電腦網路 3.考試指南</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.76</類號>
		<ISBN>978-986-476-387-0 (平裝, 216面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>新生代攝影年鑑. 2017</書名>
		<作者>房彥文總編輯</作者>
		<出版單位>中華藝術交流協會</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-94715-0-3 (精裝, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>印前製程丙級檢定學術科應檢寶典最新版: 適用Phtotoshop/Illustrator</書名>
		<作者>技能檢定研究室著</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.印刷術 2.問題集</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>477.022</類號>
		<ISBN>978-986-476-389-4 (平裝, 300面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>MTA Networking Fundamentals國際認證教戰手冊(98-366)</書名>
		<作者>吳進北, 林文恭研究室著</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/04</出版年月>
		<標題>1.網際網路 2.電腦網路 3.考試指南</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.1653</類號>
		<ISBN>978-986-476-390-0 (平裝, 216面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>公務人員退休撫卹基金統計年報. 中華民國105年</書名>
		<作者>公務人員退休撫卹基金管理委員會編著</作者>
		<出版單位>退撫基金管委會</出版單位>
		<版次></版次>
		<出版年月>106/05</出版年月>
		<標題>1.人事制度 2.公務人員 3.退休金 4.政府統計 5.中華民國</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>573.434028</類號>
		<ISBN>978-986-05-2313-3 (平裝, NT$210, 150面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>世界末日的世界錄</書名>
		<作者>細音啟作; 紅豆佳譯人譯</作者>
		<出版單位>尖端</出版單位>
		<版次>初版</版次>
		<出版年月>106/06</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-957-10-7451-1 (第9冊:平裝, 264面, 19公分)</ISBN>
	</Book>
	<Book>